### ISSUE TITLE
change music stream

### ISSUE THREAD

**Issue by ghost** [Nearata/flarum-ext-listen-moe#1]
Hello, how to change the stream music?

**Comment by Nearata** [comment]
As admin, you can only change the radio for guests.

As user, the switch is in the `user settings`.

**Comment by ghost** [comment]
yes, but this is Chinese radio, and I would like to change it to an online stream ok. radioparty.pl

**Comment by Nearata** [comment]
This extension was created specifically for [LISTEN.moe](https://listen.moe). If the radio is not available there, will not be available here.

If you are in need of an extension, i suggest you to register on [Discuss](https://discuss.flarum.org/) and open a thread under `Dev` tag.
